// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnfjhnsurabkfbkspnnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZmpobnN1cmFia2Zia3Nwbm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODA2NzMsImV4cCI6MjA1ODQ1NjY3M30.wRWIkOBgbH7FCFfES4vUkdejaQcW5DeALpC6zuYQV74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);